name: Copy repo to live publish location

on:
   push:
    branches:
      - master

jobs:
   copyfiles:
      runs-on: self-hosted
      
      steps:
      - uses: actions/checkout@v2

      - name: copy files from worker to site
        run: cd "${{ secrets.PUBLISH_LOCATION_LIVE }}"; Xcopy "${{ secrets.WORKER_LOCATION_LIVE }}" "${{ secrets.PUBLISH_LOCATION_LIVE }}" /E/H/C/I/exclude:actionrunnerexclusions.txt/Y

