name: Copy repo to live publish location

on:
   push:
    branches:
      - master

jobs:
   copyfiles:
      runs-on: self-hosted
      
      steps:
      - uses: actions/checkout@v2

      - name: copy files from worker to site
        run: Xcopy ${{ secrets.WORKER_LOCATION_LIVE }} ${{ secrets.PUBLISH_LOCATION_LIVE }} /E/H/C/I/exclude:${{ secrets.PUBLISH_LOCATION_LIVE }}\actionrunnerexclusions.txt/Y

