name: Copy repo to test publish location

on:
   push:
    branches:
      - develop

jobs:
   copyfiles:
      runs-on: self-hosted
      
      steps:
      - uses: actions/checkout@v2
      
      - name: copy files from worker to site
        run: Xcopy ${{ secrets.WORKER_LOCATION_TEST }} ${{ secrets.PUBLISH_LOCATION_TEST }} /E/H/C/I/exclude:${{ secrets.PUBLISH_LOCATION_TEST }}\actionrunnerexclusions.txt/Y

