name: Deploy Test environment to IIS

on:
  push:
    branches:
      - develop

jobs:
  deploy-test-to-iis:
    name: Deploy Test environment to IIS
    uses: happy-geeks/.github/workflow-templates/deploy-gcl-project-to-iis.yml
    with:
      action_runner_label: test
      publish_confiugration: Debug
      environment_name: Test
      publish_location: ${{ vars.PUBLISH_LOCATION_TEST }}
      application_pool: ${{ vars.APPLICATION_POOL_TEST }}
    secrets: inherit