name: Publish dev

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: juice-dev

    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Stop application pool
      run: Stop-WebAppPool -Name "${{ secrets.APPLICATION_POOL_DEV }}"
      
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o "${{ secrets.PUBLISH_LOCATION_DEV }}" --self-contained true  -r win-x64 /p:EnvironmentName=Test

    - name: Start application pool
      if: ${{ always() }}
      run: Start-WebAppPool -Name "${{ secrets.APPLICATION_POOL_DEV }}"
      
