name: Publish new releases to live environment

on:
  push:
    branches:
      - master
      - main
    tags:
    - v*

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Stop application pool
      run: Stop-WebAppPool -Name ${{ secrets.APPLICATION_POOL_LIVE }}

    - name: dotnet publish 
      run: |
        dotnet publish -c Release -o "${{ secrets.PUBLISH_LOCATION_LIVE }}" --self-contained true  -r win-x64 /p:EnvironmentName=Live
      
    - name: Start application pool
      if: ${{ always() }}
      run: Start-WebAppPool -Name ${{ secrets.APPLICATION_POOL_LIVE }}
