name: Publish new releases

on:
  push:
    tags:
    - v*

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Add NuGet Sources
      run: dotnet nuget add source --username GilianJuice --password ${{ secrets.HAPPYGEEKSNUGET }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/happy-geeks/index.json"
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Stop application pool
      run: Stop-WebAppPool -Name ${{ secrets.APPLICATION_POOL }}

    - name: dotnet publish 
      run: |
        dotnet publish -c Release -o "${{ secrets.PUBLISH_LOCATION }}" --self-contained true  -r win-x64
      
    - name: Start application pool
      if: ${{ always() }}
      run: Start-WebAppPool -Name ${{ secrets.APPLICATION_POOL }}
    
    - name: Remove NuGet Sources
      if: ${{ always() }}
      run: dotnet nuget remove source github
